### ISSUE TITLE
Fix the build/config so that running locally on Windows 'Just Works'

### ISSUE THREAD

**Issue by boydingham** [ministryofjustice/prisoner-offender-search#155]
### Expected Behavior

Following, step by step, the usage instructions in [_the "Running" section_](https://github.com/ministryofjustice/prisoner-offender-search#running) of the README, attempting to run the system locally should just work; without any need to edit anything.

### Current Behavior

The system fails to run when—following verbatim—the usage instructions in [_the "Running" section_](https://github.com/ministryofjustice/prisoner-offender-search#running) of the README ([_full stack trace_](https://github.com/ministryofjustice/prisoner-offender-search/files/6629836/prisoner.offender.search.bootrun.bombs.0.a.log))...

```bash
...
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'globalSearchResource' defined in file [D:\development\projects\yjaf\pnomis\ycd.560\knowledge.transfer\prisoner-offender-search-main\build\classes\kotlin\main\uk\gov\justice\digital\hmpps\prisonersearch\resource\GlobalSearchResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'globalSearchService' defined in file [path.to.project/prisoner-offender-search-main/build/classes/kotlin/main/uk/gov/justice/digital/hmpps/prisonersearch/services/GlobalSearchService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'indexStatusService' defined in file [path.to.project/prisoner-offender-search-main/build/classes/kotlin/main?uk/gov/justice/digital/hmpps/prisonersearch/services/IndexStatusService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'indexStatusRepository' defined in uk.gov.justice.digital.hmpps.prisonersearch.repository.IndexStatusRepository defined in @EnableElasticsearchRepositories declared on ElasticSearchConfiguration: Invocation of init method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository]: Constructor threw exception; nested exception is org.springframework.dao.DataAccessResourceFailureException: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed

...

Caused by: org.apache.http.ConnectionClosedException: Connection is closed
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:356)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:261)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.base/java.lang.Thread.run(Thread.java:831)


> Task :bootRun FAILED

...

```

### Context

I am an ***external*** developer of a ***non-DPS*** system. My system [_is specified to consume API endpoints exposed by this project_](https://prisoner-offender-search-dev.prison.service.justice.gov.uk/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/prisoner-match-resource/matchPrisoners). 

Being able to run, test and integrate my system with a local deployment of this project, would...

1. Speed up the delivery of my system
1. Simplify the development process of my system

### Steps to Reproduce 

1. Making ***zero*** changes to ***zero*** files of this project, follow verbatim the usage instructions in [_the "Running" section_](https://github.com/ministryofjustice/prisoner-offender-search#running) of the README...

![prisoner offender search dependent services up and healthy 0 a](https://user-images.githubusercontent.com/82042696/121501497-33d9de80-c9d7-11eb-87fb-cef34075f105.gif)

----

![prisoner offender search dependent services up and healthy -1 b](https://user-images.githubusercontent.com/82042696/121503565-173ea600-c9d9-11eb-8cff-a15a7e381443.gif)

### Your Environment

* Windows 10
* Docker Desktop Version 3.3.3 (64133)
* IntelliJ IDEA 2021.1.2 (Community Edition)
   - Build #IC-211.7442.40

**Comment by petergphillips** [comment]
Thanks for raising the issue.

I don't think any of us run windows either so might be tricky to fix I'm afraid.  Can I ask why you need to run the prisoner offender search in intellij?  Does docker-compose up work or doesn't that work either?

**Comment by boydingham** [comment]
...

### _TL;DR_

_I just need to call this project **somehow**_.

--

### _To be clear_
 
> "_...why you need to run the prisoner offender search in intellij?..._"

I don't "_**need** to run the prisoner offender search in intellij_", sir.

I'm not doing any development per se _**on**_ this project. That is, no code changes, no fixes, etc. 

The **_non-DPS_** project that _**I am**_ developing, consumes the resources (_endpoints_) of this project. Therefore, it would be _**ideal**_ to be able to run this project locally as I develop my **_non-DPS_** project.

However, I presume that if I was provided with adequate instructions from DPS (_or whoever_), then I could do my development by consuming _[the remote dev deployment](https://prisoner-offender-search-dev.prison.service.justice.gov.uk/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/prisoner-match-resource/matchPrisoners)_ of this project.

Whether local deployment of this project is possible from the _`docker-compose`_ command or from within an IDE—_or even if my **non-DPS** application **must** call your remote dev deployment_—**_I can be flexible_**.

**Comment by boydingham** [comment]
Thanks for [_your pgp-DT-1949-update-localstack branch_](https://github.com/ministryofjustice/prisoner-offender-search/tree/pgp-DT-1949-update-localstack) @petergphillips,

The _`localstack`_ service now starts up OK on Windows...

![prisoner offender search dependent localstack compose all ready 0 a](https://user-images.githubusercontent.com/82042696/122515502-6ef69600-d005-11eb-9924-cf7d36d4e283.gif)

...But the _`prisoner-offenders-search`_ service is still failing to start. It fails with [_the same exception originally reported_](https://github.com/ministryofjustice/prisoner-offender-search/files/6629836/prisoner.offender.search.bootrun.bombs.0.a.log)...

![prisoner offender search bootrun bombs still 0 b](https://user-images.githubusercontent.com/82042696/122527785-8e94bb00-d013-11eb-8cbf-6282b5c1ce25.gif)

**Comment by petergphillips** [comment]
As I mentioned in slack to you, yo need to wait for
```
Running on http://0.0.0.0:4571
```
output from localstack before starting prisoner offender search.  The README now also contains more detailed instructions on starting up prisoner offender search and provides two options depending on whether you want prisoner offender search to be within docker too or not.

**Comment by boydingham** [comment]
Thank you @petergphillips,
 
> _"...mentioned in slack to you, you need to wait for..."_

My Slack availability is limited. I plan to login to your channel later this afternoon though.

Also, since this is a public open source project in a public repo, then is it fair to presume that there is some value in publicly sharing whatever solutions are discovered?

By "_sharing_" I mean with potential **_non-DPS_** consumers of this project —other than myself—that might run into the same issue in the future.
